### ISSUE TITLE
Unable to find wappalyzer path

### ISSUE THREAD

**Issue by er1csg** [tristanlatr/MassWappalyzer#2]
I installed python 3.8.9 and wappalyzer. however, i encountered the error below and was wondering if you have any clues on where the error that i might have using your scripts?
-------------------------

Mass Wappalyzer
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\masswappalyzer.py", line 434, in <module>
    main()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\masswappalyzer.py", line 429, in main
    mass_w = MassWappalyzer(urls, **args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\masswappalyzer.py", line 288, in __init__
    self.analyzer = WappalyzerWrapper(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\masswappalyzer.py", line 175, in __init__
    if not self.wappalyzerpath :
AttributeError: 'WappalyzerWrapper' object has no attribute 'wappalyzerpath'

------------------------

**Comment by tristanlatr** [comment]
Hi, Thanks for the report, this should be fixed now :)

Please try again.
