### ISSUE TITLE
TypeError: Wappalyzer.latest() got an unexpected keyword argument 'update'

### ISSUE THREAD

**Issue by andreualegre** [tristanlatr/MassWappalyzer#4]
Hi, 

I am trying to run MassWappalyzer on my terminal. i have already installed everything and got my MassWappalyzer folder installed, with the script, samples, etc.

However, when I try running the command **python3 -m masswappalyzer -i websites.txt -o websites.xlsx**

It states this: 

Mass Wappalyzer
Using python-Wappalyzer
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/andreualegre/MassWappalyzer/masswappalyzer.py", line 408, in <module>
    main()
  File "/Users/andreualegre/MassWappalyzer/masswappalyzer.py", line 401, in main
    mass_w = MassWappalyzer(urls, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andreualegre/MassWappalyzer/masswappalyzer.py", line 281, in __init__
    self.analyzer = WappalyzerWrapper(
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/andreualegre/MassWappalyzer/masswappalyzer.py", line 247, in __init__
    self._analyze = PythonWappalyzer().analyze
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/andreualegre/MassWappalyzer/masswappalyzer.py", line 185, in __init__
    self._wappalyzer = self.Wappalyzer.Wappalyzer.latest(update=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wappalyzer.latest() got an unexpected keyword argument 'update'

**Comment by lmogthb** [comment]
Hello, you have to update the script and search for the value Wappalyzer.latest(update=true), there u have to remove the Argument from the function.

The result would be Wappalyzer.latest()

**Comment by sr-if** [comment]
thank you @aolmosasir
